general {
    lock_cmd = hyprlock          # command to run when idle timeout is reached
    before_sleep_cmd = loginctl lock-session  # command run before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # command run after wake-up
}

# Turn off monitor after 3 minutes
listener {
    timeout = 180                                 # in seconds
    on-timeout = hyprctl dispatch dpms off        # turn off screen
    on-resume = hyprctl dispatch dpms on          # turn on screen when activity is detected
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
    }

# Suspend after 10 minutes
listener {
    timeout = 600
    on-timeout = systemctl suspend
}


# shudown after 1 hour
listener {
    timeout= 3600
    on-timeout= hyprshutdown --post-cmd 'systemctl poweroff'
  }
