-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- NOT AUTOGENERATED HYPRLAND CONFIG.                        --
-- RICE BY DEVPADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--hl.config({ autogenerated = true }) -- remove this line to remove the warning YEAH

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

-- okay hyprland ill organize and modularize my config files haha
require("modules.defaultApps")
require("modules.keybinds")
require("modules.env")
require("modules.windowAndWorkspaces")
require("modules.startup")
require("modules.animations")
require("modules.misc")
require("modules.monitors")
require("modules.permissions")
require("modules.input")
require("modules.decorations")
